matrix:
    VARNISH_VERSION:
    - 6.0
pipeline:
# Build and push release
    build-and-push-branch:
        image: plugins/docker
        repo: fpfis/varnish
        tags: ${VARNISH_VERSION}
        build_args:
            - VARNISH_VERSION=${VARNISH_VERSION}
        secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
        when:
            event: push
